apiVersion: 1

datasources:
  - name: Obsinity API
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://obsinity-reference-server:8086
    isDefault: true
    jsonData:
      auth_method: none
      allowDangerousHTTPMethods: true
      httpHeaderName1: Content-Type
    secureJsonData:
      httpHeaderValue1: application/json
    version: 2
    editable: true
